[package]
name = "interpreter-asm"
version = "0.1.0"
edition = "2021"
authors = ["xlatbx59"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
